[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-proxy"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[template.environment]
  VITE_WEATHER_API_KEY = "Your OpenWeatherMap API Key"
  REACT_APP_FIREBASE_API_KEY = "Your Firebase API Key"
  REACT_APP_GOOGLE_MAPS_API_KEY = "Your Google Maps API Key"